cp -v ../induction_control_wes/sweep_ct.eps .
cp -v ../induction_control_wes/spectra_thrust_cthat.eps .
cp -v ../induction_control_wes/multirow.eps .
cp -v ../induction_control_wes/single_row_opt.eps .
cp -v ../induction_control_wes/individual_gains.eps .
cp -v ../induction_control_wes/fullfarm_singlerow.eps .
cp -v ../induction_control_wes/scrambled.eps .
cp -v ../induction_control_wes/vorticity.eps .
cp -v ../induction_control_wes/setup_sinusoidal.eps .
cp -v ../induction_control_wes/gains_turbulent_6D_6D_6D_wide_inphase2.eps .
cp -v ../induction_control_wes/gains_turbulent_6D_6D_6D_wide_antiphase_z0_1m2.eps .
cp -v ../induction_control_wes/pumpcases2.eps .
cp -v ../induction_control_wes/gains_row22.eps .
cp -v ../induction_control_wes/gains_fullscale.eps .
cp -v ../induction_control_wes/frontviews_allc3t5.eps .
